### ISSUE TITLE
[Request] Hide the popup when Ctrl+C hotkey pressed

### ISSUE THREAD

**Issue by emvaized** [poochie89/SnipDo-Extensions#51]
Sometimes when you select some text and press Ctrl+C to copy it, it becomes annoying that SnipDo popup remains on screen, and you have to click somewhere to hide it. Would be great to see some option to hide the popup on Ctrl+C shortcut, or any key press. 
Thanks

**Comment by poochie89** [comment]
I will add that

**Comment by emvaized** [comment]
@poochie89 
Thanks! Very appreciated

**Comment by emvaized** [comment]
I noticed that new version added "Hide on Ctrl + C" option in settings! Thanks! 
However, it doesn't work for me on Windows 11... When I press Ctrl+C, nothing happens and popup remains visible.

**Comment by emvaized** [comment]
By the way, perhaps it makes sense to hide not only on Ctrl+C, but also on Ctrl+X? Also, some text editors provide hotkeys like Ctrl+B or Ctrl+I to edit text... Maybe it should be more generic, like "Hide when Ctrl is pressed"? Thanks

**Comment by poochie89** [comment]
Can you enable logging and press ctrl c, and send me the file?
Also please try to change the mouse monitoring to v1 in the setting
(settings).



Max ***@***.***> schrieb am Fr. 16. Juni 2023 um 22:41:

**Comment by emvaized** [comment]
Sure, here's basic log: 
1) Enabled logging
2) Switched to browser and selected text (popup revealed)
3) Pressed CTRL+C 3 times
4) Popup did not dissapeared until "Autohide" setting elapsed (3 seconds)
5) Switched back to SnipDo and pressed "Export"

[log.txt](https://github.com/poochie89/SnipDo-Extensions/files/11777928/log.txt)

**Comment by poochie89** [comment]
Ok thanks,
Please also change the monitoring mode to v1 in the settings (bottom).
This should def work, but i would like to make it work with v2 as well.


Max ***@***.***> schrieb am Sa. 17. Juni 2023 um 06:49:

**Comment by emvaized** [comment]
The one I shared was with v1 mode in settings.

Here's the same log for v2: 
[log_v2.txt](https://github.com/poochie89/SnipDo-Extensions/files/11777942/log_v2.txt)

**Comment by poochie89** [comment]
3.0.50 is out, should be fixed there?

**Comment by emvaized** [comment]
Nope, still doesn't work for me with 3.0.50 unfortunately...

**Comment by poochie89** [comment]
Does it work when the show on ctrl+c option is enabled?

**Comment by emvaized** [comment]
No, not really. 
Moreover - I figured out that "Show on CTRL+C" and "Show on CTRL+X" options are not working for me either. But "Show on CTRL+A" does work and shows tooltip.

**Comment by poochie89** [comment]
Ok got the bug, fixed in next update

**Comment by emvaized** [comment]
Great, thanks!

**Comment by emvaized** [comment]
Yeap, it works just fine in 3.0.52! Thanks again for your great work.
